### ISSUE TITLE
Plugin not available in yum repo

### ISSUE THREAD

**Issue by abohne** [theforeman/foreman_host_rundeck#4]
I do not see this plugin available as an rpm from http://yum.theforeman.org/plugins/1.7/el6/x86_64/.  Will an rpm be made available for this plugin?

**Comment by domcleal** [comment]
Yeah, seems it's still waiting on a review here.  https://github.com/theforeman/foreman-packaging/pull/357

**Comment by domcleal** [comment]
Built and pushed, thanks for the reminder!
